# MAG 系统修正参数配置文件
# 所有百分比值以小数形式表示（例如：5% = 5, -10% = -10）

# =============================================================================
# 对标链背离修正
# =============================================================================
benchmark_divergence:
  # 纳指背离扣分（所有币种都需要检查，除了纳指自己）
  nasdaq: -10.0

  # BTC背离扣分（除了BTC和纳指，其他都需要检查）
  btc: -5.0

  # 龙头币背离扣分（只有小币需要检查）
  dragon_leaders:
    ETH: -2.5
    BNB: -1.5
    SOL: -1.0
    DOGE: -0.5

# =============================================================================
# 相变修正（跨越1000阈值）
# =============================================================================
phase_transition:
  # 进场期跨越修正
  entry_phase:
    upward: 5.0      # 向上跨越1000：+5%
    downward: -5.0   # 向下跨越1000：-5%

  # 退场期跨越修正（反向）
  exit_phase:
    upward: -5.0     # 向上跨越1000：-5%
    downward: 5.0    # 向下跨越1000：+5%

# =============================================================================
# 逼近修正
# =============================================================================
approaching_correction: -5.0

# =============================================================================
# 爆破指数修正
# =============================================================================
break_index:
  # 进场期第一天且爆破指数>200
  entry_phase_day1_above_200: -2.5

  # 退场期第一天且爆破指数<0
  exit_phase_day1_below_0: -2.5

# =============================================================================
# 质量评级阈值
# =============================================================================
quality_thresholds:
  # 优质：最终百分比 > excellent_min
  excellent_min: 5.0

  # 一般：最终百分比 >= poor_max
  # 劣质：最终百分比 < poor_max
  poor_max: -5.0

# =============================================================================
# 系统设置
# =============================================================================
system:
  # 配置文件版本（用于未来兼容性检查）
  config_version: "1.0"

  # 是否启用配置验证
  enable_validation: true
